<?php 
/** @var $block \Biglidio\MiniBlog\Block\Post\View */
$posts = $block->getPosts();
?>

<h1><?= __('List of Posts') ?></h1>

<ul>
    <?php foreach ($posts as $post): ?>
        <li>
            <p><strong>Title:</strong> <?= $post->getTitle() ?></p>
            <p><strong>Tags:</strong> <?= $post->getTags() ?></p>
            <p><strong>Author:</strong> <?= $block->getAuthorName($post->getAuthorId()) ?></p>
            <br>
        </li>
    <? endforeach; ?>
</ul>